CREATE USER IF NOT EXISTS
'${DB_GRAFANA_USER}'@'%' IDENTIFIED BY '${DB_GRAFANA_USER}';
CREATE DATABASE IF NOT EXISTS grafana;
CREATE TABLE IF NOT EXISTS ${GRAFANA_DB}.user(
id 
bigint primary key AUTO_INCREMENT,

name 
text 
NOT NULL, 

age int 
NOT NULL);

GRANT SELECT ON ${GRAFANA_DB}.user
TO '${DB_GRAFANA_USER}'@'%'
