services:
  minio:
    container_name: minio
    build:
      context: ./minio/
    volumes:
      - ./minio/configs/:/minio/:ro
      - minio_volume:/mnt/data/
      - ./prometheus/scrapes.d/:/scrapes.d
      # note that address is for api, and console-address is for webui primary
    command: minio server /mnt/data --license /minio/minio.license --address=minio:$MINIO_API_PORT --console-address=minio:$MINIO_WEBUI_PORT
    env_file:
      - path: ./minio.env
    environment:
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is required}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?MINIO_ROOT_PASSWORD is required}
      MINIO_API_PORT: ${MINIO_API_PORT:?MINIO_ROOT_PASSWORD is required}
      MINIO_WEBUI_PORT: ${MINIO_WEBUI_PORT:?MINIO_WEBUI_PORT is required}
    ports:
      - $MINIO_WEBUI_PORT:$MINIO_WEBUI_PORT
      - $MINIO_API_PORT:$MINIO_API_PORT
      # TODO: add healthcheck and for that check: https://docs.min.io/aistor/reference/cli/mc-ready/ https://stackoverflow.com/questions/66412289/minio-add-a-public-bucket-with-docker-compose
    healthcheck:
      # test: ["CMD", "mc", "ping", "--count=1", "local"]
      test: ["CMD", "mc", "ping", "--count=1", "local"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.13.4
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/scrapes.d:/etc/prometheus/scrapes.d/
    ports:
      - 127.0.0.1:9090:9090 
    depends_on:
      minio:
        condition: service_healthy

volumes:
  minio_volume:
    driver: local
    driver_opts:
      device: ./minio/minio_data/
      type: none
      o: bind
