scrape_configs:
    - job_name: minio-job
      bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiVDdNWEVOWVgzQ0NYV1NIOVoxSFQiLCJleHAiOjQ5NDUyODExNDN9.nFD_NkQykWNG_J_b8ZoxmgAnHkiAoDDvu0KZ8e_zCSWld0rTywC8O0SloyjT6ElGUZ1Z6x02oi3wbG1F91VvEg
      metrics_path: /minio/v2/metrics/cluster
      scheme: http
      static_configs:
        - targets: ['minio:9999']
